### ISSUE TITLE
Update JSON input method to reduce memory burden

### ISSUE THREAD

**Issue by colditzjb** [CRMTH/RITHM#3]
The current method of inputting raw tweet data requires the entire file to be loaded into working memory for formatting. In order to make the file object JSON-compliant, the entire file object is transformed. First, a header and footer are added to enclose all of the tweet objects together. Then, regex replacements are made to insert commas between tweet objects, which are easily located as curly braces butting up against each other like "}{". Then each tweet object is read from the reformatted JSON formatted object in working memory.

It would be more memory efficient to read the file either line-by-line (if each tweet is stored on a separate line, which I *don't* think is the case) or to read the file until "}{" is reached (which would indicate the end of one JSON object and the beginning of another). Then pass a single tweet object (which should be JSON compliant) to a variable for parsing, then continuing to read the raw data file from where we left off.  Here's a StackOverflow article about a similar issue, though it doesn't address this particular issue of interrupting `readlines` based on file contents: https://stackoverflow.com/questions/6475328/read-large-text-files-in-python-line-by-line-without-loading-it-in-to-memory 

Essentially, it would be better to be able to pull out one tweet object at a time and convert that to JSON, rather than trying to load and translate a much larger data file in working memory.  This would allow the parser to scale down to systems with smaller memory allocations. Also, this may remedy problems that occur when data filed terminate abruptly (e.g., the streamer crashed while midway through writing a tweet object). That way, only the last tweet object is corrupted instead of the entire file!

Additional details of current input conventions are explained in the MagicBird Wiki:
https://github.com/CRMTH/MagicBird/wiki/Background:-Data-Format

**Comment by CRMTH** [comment]
@CRLarkin - we're going to close this up over the next couple weeks. If you have anything to add, please do!

**Comment by colditzjb** [comment]
This has been integrated into the newest version of parser.py
